number-sections: true
format:
  html:
    page-layout: full
    include-in-header:
      - includes/metrics.html
      - includes/pseudocode-header.html
    include-after-body: includes/pseudocode-footer.html
    date-format: long
    toc-title: >
      <a href="https://computo.sfds.asso.fr"><img style="width: 96px;" alt="Computo" src="https://computo.sfds.asso.fr/assets/img/logo_text_vertical.svg"/></a> <br/><br/>
      Contents
    toc: true
    theme: cosmo
    license: "CC BY"    
    hover-citations: true
    hover-footnotes: true
    highlight-style: github
    code-background: true
    code-border-left: "#31BAE9"
    code-tools:
      source: true
      toggle: false
      caption: "source"
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    html-math-method: katex
    self-contained: true
crossref:
  sec-prefix: Section
  eq-prefix: Equation
  fig-prefix: Figure   
  tbl-prefix: Table

